### ISSUE TITLE
config as dict?

### ISSUE THREAD

**Issue by pjz** [willkg/everett#132]
Is there a way to get a config or namespace as a dict?  I have other components that take their defaults from a dict and I'd like to be able to pull that dict from a config file that gets loaded by Everett.

**Comment by willkg** [comment]
You could traverse the configuration to generate a dict. I use this for logging configuration:

```
def log_config(logger, component):                                                       
    """Log configuration for a given component."""                                       
    for namespace, key, val, opt in component.get_runtime_config():                      
        if namespace:                                                                    
            namespaced_key = "%s_%s" % ("_".join(namespace), key)                        
        else:                                                                            
            namespaced_key = key                                                         
                                                                                         
        namespaced_key = namespaced_key.upper()                                          
                                                                                         
        msg = "%s=%s" % (namespaced_key, val)                                        
        logger.info(msg)                   
```

https://everett.readthedocs.io/en/latest/library.html?highlight=get_runtime_config#everett.component.RequiredConfigMixin.get_runtime_config

Does something like that help you build what you need?

**Comment by pjz** [comment]
Ah! That would do it, thanks!  Though it looks like perhaps the docs are wrong, as they say `get_runtime_config()` returns "list of (namespace, key, option)" but you're getting (namespace, key, val, opt) ... or am I misunderstanding something?

**Comment by willkg** [comment]
Oops--looks like the docs are wrong. I'll fix that.

**Comment by pjz** [comment]
Hmm, looking again, that only works for required config keys - is there a way to get _all_ the config key/values as a dict?  Looking at the impl of the the `get()` methods on the `Config*` objects in manager.py, I'm guessing the answer may be 'no'.

**Comment by willkg** [comment]
Why do you think it only works for required config keys? Can you show me an example?

**Comment by pjz** [comment]
because it's on the RequiredConfigMixin ?

**Comment by willkg** [comment]
The RequiredConfigMixin covers all configuration for a component. What configuration are you seeing missing?

**Comment by pjz** [comment]
My config has no required keys, so isn't using the RequiredConfigMixin.  I'm looking to get the contents of a namespace as a dict so I can pass it to a different thing I have that takes its config options as a dict.

**Comment by willkg** [comment]
Huh. I guess I don't understand what you're doing. Can you point me to the code or post it?

**Comment by pjz** [comment]
I just want to get a dict of all specified config keys and their values.  All I can currently see is a way to query 'get key X', and no way to say 'get me all specified keys'.

**Comment by pjz** [comment]
Code example (from the documentation):
```
import os
import sys

from everett.ext.inifile import ConfigIniEnv
from everett.manager import ConfigManager, ConfigOSEnv

'''
example config file:
---
debug=True
[hosts]
example.com=127.0.0.1
'''

def build_config_manager():
    return ConfigManager(
        # Specify one or more configuration environments in
        # the order they should be checked
        environments=[
            # Look in OS process environment first
            ConfigOSEnv(),

            # Look in INI files in order specified
            ConfigIniEnv([
                os.environ.get("MYAPP_INI"),
                "~/.myapp.ini",
                "/etc/myapp.ini"
            ]),
        ],

        # Provide users a link to documentation for when they hit
        # configuration errors
        doc="Check https://example.com/configuration for docs."
    )
    
config = build_config_manager()

#  existing functionality, known key
debug = config('debug')

#  what I'd like to be able to call but can't.  would return { 'example.com': '127.0.0.1'}
dns_overrides = config.ns_as_dict('hosts')  

```

Now I want to get all the keys in the `hosts` namespace.  I can get any known key via `config(key, namespace)`... but I don't know of a way (there may not be a way?) to get the list of all keys in a particular namespace.

**Comment by willkg** [comment]
Aha! You're not using Everett components. So, no--Everett doesn't have anything that can give you all the things without you telling it what to look for with something like a component with `RequiredConfigMixin`.

**Comment by willkg** [comment]
I'm going to close this out since I don't think there's anything to do here.

**Comment by pjz** [comment]
FWIW, I ended up writing https://github.com/pjz/mincfg to do what I needed.  Not helpful for everett, though.
