### ISSUE TITLE
figure out how to use config() in a DRY way without screwing up config override

### ISSUE THREAD

**Issue by willkg** [willkg/everett#14]
Say you have an app where you're doing a lot of things based on some `DEBUG` variable. You have a couple of options for implementation:
1. you could cache the value of `config('DEBUG', parser=bool)`, but that potentially screws up using config override in the tests
2. you could write `config('DEBUG', parser=bool)` over and over again, but that's awful for a variety of reasons

@ErikRose dislikes defining the types at call time, too, for similar reasons to the above.

This issue covers figuring out a better way to do this.

**Comment by willkg** [comment]
Maybe we introduce another layer along the lines of an app config. Maybe it works like a component and you define all your configuration centrally there and then refer just to keys throughout your code. Something like this:

```
class AppConfig(RequiredConfigMixin):
    required_config = ConfigOptions()
    required_config.add_option('debug', parser=bool)
    ...

    def __init__(self, config):
        self.config = config.with_options(self)

    def __getitem__(self, key):
        return self.config(key)
```

Then in your app initialization, you'd create the ConfigManager and then your AppConfig instance. Abusing getitem notation, we could have something like this:

```
def get_app():
    config = ConfigManager([
            ConfigOSEnv(),
            ConfigIniEnv([
                os.environ.get('FOO_INI'),
                '~/.foo.ini',
                '/etc/foo.ini'
            ]),
        ])
    app_config = AppConfig(config)

    debug = app_config['debug']
```

Or something like that.

This is helpful in certain situations. You wouldn't use this in conjunction with Django settings, but you might use it in a Flask app or a web.py app.

Worth thinking of other options here.

**Comment by erikrose** [comment]
I think the layering division of…

1. Selection (Decide what source value to use, among env vars, files, etc.)
2. Transformation (Turn the selected source value into whatever representation is convenient to the program: an int, a fancy object, a list of strings, etc. While we're at it, validate (which might be a separate layer but probably not).)
3. Presentation (Make the transformed value conveniently available where the program needs it.)

…might be an aid to thinking here. In my mind, those are the concerns that any config lib might address. Explicitly decoupling them in a library would make it usable in more situations.

It also might be freeing, in temrs of later places to hang bits of API, to represent as many things as first-class objects as possible. For instance, if we had a first-class representation of a config option, say, `app_config.debug_option`, we would have the option of hanging something like `debug_option.validate(…)` off that. This really comes into play with "compound options", like "everything you need to address a RabbitMQ server". You can define its validation rules once, then make a copy of that option group for each Rabbit server you need to configure.

**Comment by willkg** [comment]
@erikrose's division of layers in Everett is sort of like this:

1. selection: configmanager
2. transformation: parsers (these essentially validate as well as parse since they convert things from string to something else and you can't convert what isn't convertable)
3. presentation: ?

The presentation layer could be a component like I suggested in https://github.com/willkg/everett/issues/14#issuecomment-240238052. That's how I wrote Antenna. It's got some really nice things about it:

1. configuration is defined in a single place and can be used wherever without repeating bits like defaults and parsers and such
2. you can add business logic to the configuration in the same component--it's just a class instance
3. Everett has a Sphinx autoconfig thing that can take that component and generate HTML documentation from it which is super handy
4. Everett has a `get_runtime_config()` which you can use to print out runtime configuration at startup which is handy in certain situations

I added a recipe for this in #40.

Given that, I think I've got as far as I'm going to get with this. We can tweak it going forward as new challenges present themselves.
