### ISSUE TITLE
Namespaces don't pick up configuration defaults

### ISSUE THREAD

**Issue by ebielefeldt** [willkg/everett#175]
First off, this is a great repo, it's super useful!

Hopefully, this isn't a case of RTFM, but it appears that config class defaults are not respected when using namespaces.  Here is example code that illustrates the issue I'm running into:

```python
from everett.manager import Option
from everett.manager import ConfigManager, ConfigOSEnv


class AppConfig:
    class Config:
        http_port = Option(default="80")


config = ConfigManager(environments=[ConfigOSEnv()]).with_options(AppConfig())

print(config("http_port"))  # Prints 80 as expected

print(config.with_namespace("http")("port"))  # Raises ConfigurationMissingError
```

Looking at the source code, it _seems_ like the issue is that `NamespacedConfig` does not get the options passed to it.  If I'm missing something though, please point me in the right direction to get this working.

**Comment by willkg** [comment]
`.with_options()` restricts the domain of all configuration to just the configuration specified by the component and components in Everett can be in multiple namespaces, so you need to apply the namespace and then restrict the options to the ones the component specified.

So your code should be something like this:

```python
from everett.manager import Option
from everett.manager import ConfigManager, ConfigOSEnv


class AppConfig:
    class Config:
        http_port = Option(default="80")


config = ConfigManager(environments=[ConfigOSEnv()])

app_config = config.with_namespace("http").with_options(AppConfig())

print(app_config("port"))
```

I skimmed the documentation and this doesn't seem wildly obvious. I should fix it.

Having said that, do you have a use case for doing the operations in the other order? When would you want to restrict configuration to what a component defines before applying a namespace?

**Comment by ebielefeldt** [comment]
Thanks for getting back to me, and apologies for the late response.  My use case was to have a single overall config, but then pass portions of it to individual components to use.  For example, if I had a service that had some `http` settings, and some `db` settings, I was intending to do something like this:
```
from everett.manager import Option
from everett.manager import ConfigManager, ConfigOSEnv


class AppConfig:
    class Config:
        http_port = Option(default="80")
        http_host = Option(default="localhost")

        db_port = Option(default="3306")
        db_host = Option(default="database")

config = ConfigManager(environments=[ConfigOSEnv()]).with_options(AppConfig())

init_server(config.with_namespace("http"))

init_db(config.with_namespace("db"))
```
If I were to follow your suggestion, I guess I would do something like this, although it feels a bit redundant:
```
init_server(config.with_namespace("http").with_options(AppConfig()))

init_db(config.with_namespace("db").with_options(AppConfig()))
```

**Comment by willkg** [comment]
Huh. I'm not sure I would have set things up that way, but I don't think there's any reason it shouldn't work the way you want.

I'll look into changing it.

**Comment by willkg** [comment]
I think that should fix it. The test is based on your example and that works now. I'll do a release as soon as I can with this.

**Comment by ebielefeldt** [comment]
Thanks for tackling this!  I'll try pulling the latest and testing my use case.

**Comment by willkg** [comment]
I did a 3.0.0 release earlier today. Let me know how it goes!
