### ISSUE TITLE
should configinienv look at multiple ini files or just one?

### ISSUE THREAD

**Issue by willkg** [willkg/everett#2]
Currently, the ConfigIniEnv uses the first path that exists in the list of specified possible paths.

We could change it so that it uses all the existing ini files and searches through them in the order specified. This would allow you to do something like have common configuration in one file and then deviation configuration for specific environments (e.g. prod and stage) in separate files.

It's probably not hard to support, but it's not clear the use case is super compelling and can't be handled in other ways.

Needs some thought and experimentation.

**Comment by pmac** [comment]
I'm +1 on this. It would much more easily enable the use of checked in files along with secrets in a local.ini. I don't personally often do that, but I know a lot of setups still rely on files like this over environment variables.

**Comment by willkg** [comment]
There are two possible behaviors here:

1. here's a list of paths--use the first valid ini file you find in that list and ONLY that one
2. here's a list of paths--pull configuration from them in order specified so that earlier ones override values in later ones

Currently Everett implements the first one. I wrote up this issue wondering whether we should switch to the second one or handle it somehow.

@pmac mentioned on IRC that we could do this:

```
from everett.manager import ConfgManager, ConfigIniEnv

config = ConfigManager([
    ConfigIniEnv([os.environ.get('FOO_INI')]),
    ConfigIniEnv(['dev.ini']),
    ConfigIniEnv('base.ini'),
])
```

That creates the second behavior.

Given that, I'll just tweak the docs.

**Comment by willkg** [comment]
Documentation was added in pr #9.
