### ISSUE TITLE
should raise_error be renamed?

### ISSUE THREAD

**Issue by willkg** [willkg/everett#5]
@pmac pointed out that `raise_error` is a mechanical name and not semantic, so it's not very descriptive and doesn't lend itself to obviousness in how/when you'd use it.

He suggested `required` or `missing_ok`.

I've seen `required` before. I think that'd be ok. The only thing that causes me pause is that I think changing it to `required` suggests a specific use case and I'm not sure offhand whether there are other use cases where the word "required" isn't clear.

**Comment by pmac** [comment]
I can't think of any off-hand, but I agree it's possible. I guess it's mostly about me not wanting to write `raise` in my config 😆

**Comment by willkg** [comment]
After using this a bunch, I'm currently thinking the mechanicalness is ok here since it's programmer-focused and there are a bunch of use cases in which you'd want to specify not to raise an error if the config item isn't there that have nothing to do with whether it's required or not.

Given that, I'm going to close this out.
