### ISSUE TITLE
support Windows registry as a configuration source

### ISSUE THREAD

**Issue by petri** [willkg/everett#52]
Following the convention, I guess that could be called ConfigRegistryEnv.

A few questions:

1. Is it ok to include this in Everett or would you rather see it as a separate package?
1.1 If it is ok, can this be included in the main package or should it rather be distributed as an optional package extra, say, [windows]?
1. Is it ok to introduce a dependency ([regpath](https://pypi.python.org/pypi/regpath))? The built-in winreg module is of course sufficient, but regpath makes it **a lot** simpler to deal with the registry. It is a small package and only depends on Python3 stdlib itself (winreg & pathlib, which is in stdlib since 3.4).

**Comment by petri** [comment]
It occurred to me that we could of course check `platform.system()` in setup.py and set the `install_requires` parameter based on that. So that way, regpath would never get pulled in on non-Windows platforms. Would that be an optimum solution that should be used?

**Comment by willkg** [comment]
This isn't something I'm going to do or probably support. I think this would be great as a separate library. You could call it everett-windows or whatever works for you.

**Comment by willkg** [comment]
@petri Did you end up writing a library or find one?

**Comment by petri** [comment]
No. Haven't had the time, no idea when or if I will. I do have several projects with configuration requirements that'd everett would be a good match for though.

**Comment by willkg** [comment]
@petri Is this something you still want and have time to implement? If not, I'm probably going to nix it.

**Comment by willkg** [comment]
Per the previous comment, I'm closing this out.
