### ISSUE TITLE
Docs seem self contradictory?

### ISSUE THREAD

**Issue by pjz** [willkg/everett#54]
https://github.com/willkg/everett/blob/master/everett/manager.py#L328

says:

```    Namespace is prefixed, so key "foo" in namespace "bar" is ``FOO_BAR``. ```

... and the first assertion 'Namespace is prefixed' seems to contradict the example, which has the namespace at the end.

Which is correct?

**Comment by willkg** [comment]
It's backwards--my bad. I fixed it in 402b4ef.

Thank you!
