### ISSUE TITLE
Feature request: support yaml config files

### ISSUE THREAD

**Issue by pjz** [willkg/everett#72]
Lots of people like yaml config files, and they have some nice properties (they merge well in version control, they're pretty readable, etc).  It would be good to support them, so they could be used as well as or instead of ini files.

**Comment by willkg** [comment]
I want to do this.

One of the things I was balking at is that it needs a bunch of libraries to do it. I think I want to do an API-breaking version of Everett and move environments into their own modules and do optional requirements. I did similar things with Markus, so I think that should work fine.

**Comment by willkg** [comment]
I wrote up #79 to cover splitting things out. I think once we do that, this will be pretty straight-forward.

**Comment by willkg** [comment]
I'm thinking of something along these lines:

1. key-value syntax
2. nested keys are concatenated together with `_` to form namespaced keys
3. only allows string values

So these two yaml files are equivalent:

```
# some yaml configuration
name: webserver1
web:
    host: localhost
    port: 5432
```

and:

```
# some yaml configuration
NAME: webserver1
WEB_HOST: localhost
WEB_PORT: 5432
```

And gives the following keys:

* `NAME`
* `WEB_HOST`
* `WEB_PORT`

I think that's in line with the other environments.

Does that sound ok?

**Comment by willkg** [comment]
Also, we might want to suggest people use double-quotes for all their values.

**Comment by willkg** [comment]
Also, also, I think I'm going to use `safe_load` which is less "interesting" in how it parses objects.

**Comment by pjz** [comment]
All sounds good.  And yes, do use `safe_load`.  Regularity and well-defined behavior are good things.
