### ISSUE TITLE
add debug-level logging for key discovery

### ISSUE THREAD

**Issue by dsblank** [willkg/everett#74]
Looking for a way to report back to user on which config file(s) are being used, and perhaps order of preference when looking up a value.

**Comment by dsblank** [comment]
Or is it possible to report where a particular variable comes from?

**Comment by willkg** [comment]
I think you're really asking these questions:

> Is there a way to list the environments for a config manager in the order they'd be checked?

You can iterate over the config manager's environments. The order of that list is the order in which they're checked. You can communicate to the user whatever you want from that.

Let me know if that works for you.

> Is there a way to know where a config value came from?

No, there isn't.

The ``__call__`` method can only return the parsed value--there isn't room in that to also return the environment from whence it came or the final key used. We could add logging, but that's not a convenient form for you to package up and communicate to the user. I'm not sure what other options there are.

Do you have ideas on how to do this?

**Comment by pjz** [comment]
You could add another flag to `__call__` like `raw_value` that was instead maybe `src_env` that of course defaults to false.  Then right before the `try..except` at [manager.py:976](https://github.com/willkg/everett/blob/master/everett/manager.py#L976)   you put something like:

    if src_env:
        return env

and then of course handle the 'use the default' and 'not present' cases as well.

**Comment by dsblank** [comment]
At the least, having a standard Python logger would be fairly useful when debugging items. If it showed (when set to DEBUG mode) something like:

```
Everett Config variables can be defined in (in order of preference):
1. OS Environment
2. ~/config.ini
3. ./config.ini
```
And when searched (if I understand your search algorithm correctly):
```
Looking up variable "VARIABLE"...
    Searching in "./config.ini" ... not found.
    Searching in "~/config.ini" ... FOUND!
    Searching in OS Environment... FOUND! 
Returning value "42" from OS Environment.
```

**Comment by dsblank** [comment]
At the least, we could have the user run with DEBUG mode on, which would report the settings.
